# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeeDrive' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FreeeDrive
platform :ios, '7.0'
pod 'Firebase'
pod 'Firebase/Messaging'


source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'
pod 'TwilioClient', '~>1.2'
pod 'FRHyperLabel'

  target 'FreeeDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeeDriveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
